// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Session struct {
	Token  interface{}
	Data   []byte
	Expiry interface{}
}

type Snippet struct {
	ID      interface{}
	Title   string
	Content string
	Created interface{}
}

type User struct {
	ID             interface{}
	Name           string
	Email          string
	HashedPassword interface{}
	Created        time.Time
	CONSTRAINT     interface{}
}
