// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package repository

import (
	"context"
)

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT true FROM users WHERE id = ?)
`

func (q *Queries) UserExists(ctx context.Context, id interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
