// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	AuthenticateUser(ctx context.Context, email string) (AuthenticateUserRow, error)
	CreateSnippet(ctx context.Context, arg CreateSnippetParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetSnippet(ctx context.Context, id string) (Snippets, error)
	LatestSnippets(ctx context.Context) ([]Snippets, error)
	UserExists(ctx context.Context, id string) (int64, error)
}

var _ Querier = (*Queries)(nil)
